registering user and return jwt token-184672388
atlp-rwanda/Team-furebo-E-commerce-bn pull request #26
Opened 2023-03-21 11:09 UTC by JulesNIYOMWUNGERI

#### What does this PR do?
On successful registration, users should receive a JWT
#### Description of Task to be completed?
- creating user registration endpoint
- validating the received credentials 
- testing if user is created in database and generate jsonwebtoken

#### How should this be manually tested?

- cloning the repo
- open in vscode or other editor
- in terminal run npm install (to install required dependencies)
- start the project by npm start
- open postman and go to localhost:3000/api/register

#### What are the relevant pivotal tracker/Trello stories?
#184672388

2023-03-21 11:11 UTC, ruberwa approved these changes, later dismissed

2023-03-21 11:17 UTC, bahati10 approved these changes, later dismissed

2023-03-21 11:34 UTC, kagame8732 submitted a review, later dismissed

2023-03-21 17:29 UTC, Raphaela664 submitted a review, later dismissed

2023-03-22 08:01 UTC, furebo requested changes

2023-03-22 08:01 UTC, furebo commented on src/controllers/user.controller.js
> +exports.create = async(req, res) => {
Please use ES6 . You need to use 'import' instead of 'require' .

2023-03-22 08:01 UTC, furebo commented on src/routes/user.routes.js
> +
Please use ES6

2023-03-22 08:01 UTC, furebo commented on src/routes/user.routes.js
> +    router.post("/register", userController.create);
Please use ES6

2023-03-22 08:01 UTC, furebo commented on src/validation/validator.js
> +const Joi = require("joi");
Use "import" instead of "require"

2023-03-22 08:01 UTC, furebo commented on index.js
>  const swaggerUi = require('swagger-ui-express');
Use ES6 (import) to import the packages instead of (ES5) require

2023-03-22 08:18 UTC, furebo requested changes, later dismissed

2023-03-22 08:18 UTC, furebo commented on src/config/config.json
>      "host": "127.0.0.1",
You need to use environment variables. So please consider use the javascript configuration file instead of json file.

2023-03-22 08:18 UTC, furebo commented on src/config/config.json
>      "host": "127.0.0.1",
You need to use environment variables. So please consider use the javascript configuration file instead of json file.

2023-03-22 08:18 UTC, furebo commented on src/config/config.json
>      "dialect": "postgres"
You need to use environment variables. So please consider use the javascript configuration file instead of json file.

2023-03-22 10:30 UTC, didasmbalanya requested changes, later dismissed
Please work on the above ASAp

2023-03-22 10:30 UTC, didasmbalanya commented on index.js
> +require('dotenv').config();
```suggestion
import 'dotenv/config'
```

2023-03-22 10:30 UTC, didasmbalanya commented on .babelrc
> -    ]
Why did you remove this?

2023-03-22 10:30 UTC, didasmbalanya commented on index.js
> + */
Move all this to the routes

2023-03-22 10:30 UTC, didasmbalanya commented on index.js
> +require('./src/routes/user.routes')(app);
Use es6 and a route handler

2023-03-22 10:30 UTC, didasmbalanya commented on src/migrations/20230317073711-create-user.js
>  module.exports = {
use ES6

2023-03-27 16:32 UTC, ruberwa approved these changes, later dismissed

2023-03-28 07:18 UTC, ruberwa approved these changes

2023-03-28 07:32 UTC, kagame8732 approved these changes

2023-03-28 07:37 UTC, bahati10 approved these changes

2023-03-28 08:05 UTC, bstwagir approved these changes

2023-03-28 08:15 UTC, merged