Fix: Remove incorrect entries from .prettierignore file
atlp-rwanda/Team-furebo-E-commerce-bn pull request #28
Opened 2023-03-22 15:46 UTC by Raphaela664

Fix: Remove incorrect entries from .prettierignore file

The previous version of the .prettierignore file contained several lines that were incorrect due to previous rebasing and merging. This commit removes these incorrect entries and ensures that the file is correctly formatted.

This fix ensures that the Prettier code formatter will correctly ignore the specified files and directories, improving the overall code quality of the project.

#184651322

2023-03-24 08:05 UTC, ruberwa requested changes

2023-03-24 08:05 UTC, ruberwa commented on .prettierignore
> +
.prettierignore still has no resolved

2023-03-24 08:11 UTC, Raphaela664 commented on .prettierignore
> +
The lines in red were deleted

2023-03-27 10:46 UTC, ruberwa approved these changes

2023-03-27 10:47 UTC, nshutip approved these changes
well executed!

2023-03-27 11:20 UTC, merged