App Logout Functionality
atlp-rwanda/Team-furebo-E-commerce-bn pull request #31
Opened 2023-03-27 14:59 UTC by bahati10

### **What does this PR do?**
Adds log-out functionality to the project
##### **Description of Task to be completed?**
Users should be able to log out of the application
As a user, I want to click on the "logout" link So 
that I get logged out of the application When a 
user clicks on the logout link, they should be 
signed out of the application with their session ended.

#### How should this be manually tested?
- First Clone the repository  
- Navigate to the branch project 
- use **`npm install`** to install the required dependencies.
- to test use **`npm run test`** and see the coverage.
- use **`npm start`** to start the server
- Navigate to the project URL `http://localhost:3000`
- Login with email and you will be redirected to 
  the protected page
- Click the **Logout** button to log out.

#### What are the relevant pivotal tracker/Trello stories?
[#184651324](https://www.pivotaltracker.com/n/projects/2633635)

2023-04-18 08:26 UTC, ruberwa approved these changes, later dismissed

2023-04-18 09:04 UTC, heshima18 submitted a review, later dismissed

2023-04-18 09:59 UTC, bstwagir approved these changes, later dismissed
Looks good.

2023-04-18 11:23 UTC, furebo requested changes, later dismissed
Please rebase from develop and make sure you don't delete the completed works.

2023-04-18 11:23 UTC, furebo commented on README.md
> -[![Maintainability](https://api.codeclimate.com/v1/badges/7322a671c14645284094/maintainability)](https://codeclimate.com/github/atlp-rwanda/Team-furebo-E-commerce-bn/maintainability) [![Test Coverage
Why have you deleted this ?

2023-04-18 11:23 UTC, furebo commented on README.md
> -- `.circleci` This folder contains the configuration file for the integration of all the testing webhooks that verify any pushed code to develop. I.e. CircleCI, Coveralls, CodeClimate.
why have you deleted these project description in this file ?

2023-04-18 11:23 UTC, furebo commented on package.json
> -    "coverage": "nyc report --reporter=text-lcov | tee coverage.lcov | coveralls && ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info",
Why have you removed these lines for running codeclimate when the tests run and the coverage on code climate ?

2023-04-25 08:25 UTC, nshutip approved these changes, later dismissed

2023-04-25 08:47 UTC, ruberwa approved these changes, later dismissed

2023-04-25 12:05 UTC, JulesNIYOMWUNGERI approved these changes, later dismissed

2023-04-28 09:18 UTC, Raphaela664 approved these changes
Great job on this pull request

2023-04-28 10:03 UTC, nshutip approved these changes
Remember to ignore the coverage folder in your next PRs.

2023-05-01 16:14 UTC, merged