feat(DB):add login endpoint
atlp-rwanda/Team-furebo-E-commerce-bn pull request #42
Opened 2023-04-03 17:40 UTC by bstwagir

-authenticate user's email and password
-if both are valid redirect user with access

[Delivers #184651331]

feat: add api
[Delivers #184651331]

feat: add api login endpoint

-authenticate email and password
-if both are valid redirect userr

[Delivers #184651331]

#### What does this PR do?
Integrate Coveralls code coverage service

#### Description of Task to be completed?

-  Sign up for a Coveralls account and generate an API key. https://coveralls.io/ 

-  Install the necessary NPM packages for code coverage. 
   npm install --save express nyc coveralls
   npm install --save-dev mocha chai 

- Sign up for a ciclici account and give coveralls API key environment variable. https://circleci.com/

- Set up your Node.js/Express application

- Configure CircleCI to run your tests and generate code coverage reports

- Add some sample tests using mocha and chai 

- configure .circleci/config.yml to upload the code coverage report to Coveralls using the generated API key 
- Verify that the code coverage report is being sent to Coveralls correctly and that you can view the coverage results on the Coveralls dashboard.

#### How should this be manually tested?
- Clone, 
- Navigate to the project 
- In the terminal type: npm install to install the required dependencies.
- for test coverage: npm run test

by running 'npm run test' you can see the coverage

#### What are the relevant pivotal tracker/Trello stories?
#184651324

2023-04-04 08:31 UTC, Raphaela664 approved these changes, later dismissed

2023-04-04 08:35 UTC, nshutip reviewed
The changes are well implemented but the PR name and description are do not meet the engineering playbook standards, and are therefore confusing.

2023-04-04 09:27 UTC, didasmbalanya requested changes, later dismissed

2023-04-04 09:27 UTC, didasmbalanya commented on src/controllers/login.controller.js
> +        { expiresIn: '7d', }
Set this a configurable. i.e as an env variable but with a default value

2023-04-04 09:27 UTC, didasmbalanya commented on src/tests/app.test.js
> +    const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJpYXQiOjE2ODA1NzQ5OTQsImV4cCI6MTY4MTE3OTc5NH0.843FO-wtu3P-rVAG5VIGFB0Ph3VT_dkCncMFrY0sxOI';
Why not generate a token here? This will fail the tests in the future after the token expires

2023-04-04 10:02 UTC, heshima18 commented on src/tests/app.test.js
make auto generated tokens to prevent the tests from failing in  the upcoming time

2023-04-04 10:04 UTC, heshima18 requested changes
update the token concept

2023-04-09 08:06 UTC, JulesNIYOMWUNGERI submitted a review, later dismissed

2023-04-09 18:36 UTC, kagame8732 approved these changes
Well designed

2023-04-10 09:20 UTC, JulesNIYOMWUNGERI approved these changes

2023-04-10 09:30 UTC, ruberwa requested changes
Functionalities ok, but something is missing

Most cases are covered but this: 

When End-User's login fails, Supposed to see clear messages of what is wrong like 
[x] Your Email is invalid or something else just to let the user know that is giving wrong inputs: When something else, not email is given

2023-04-10 09:30 UTC, merged