fixing the functionalities in getItems and searchProduct tasks -#184651344-#184651352
atlp-rwanda/Team-furebo-E-commerce-bn pull request #50
Opened 2023-04-19 08:22 UTC by JulesNIYOMWUNGERI

#### What does this PR do?
This PR is for fixing some functionalities in getItems and searchProduct tasks
#### Description of Task to be completed?

- In getItems task when there is no products on the page requested, It will return status of 404, and message describes it.
- In searchProduct task when requested product is not found, it will return status of 404, and message describes it 

#### How should this be manually tested?

#### What are the relevant pivotal tracker/Trello stories?

- #184651344
- #184651352

2023-04-19 08:47 UTC, bahati10 submitted a review, later dismissed
Looks Good

2023-04-19 08:58 UTC, kagame8732 submitted a review, later dismissed
Now get Item and search product working property.

2023-04-19 16:20 UTC, nshutip approved these changes, later dismissed
Receiving the variables from the request body is a better practice.

2023-04-20 08:20 UTC, didasmbalanya requested changes, later dismissed

2023-04-20 08:20 UTC, didasmbalanya commented on src/controllers/searchProducts.controller.js
> +    } = req.query;
use a validation middleware to check for this values

2023-04-25 13:52 UTC, ruberwa approved these changes

2023-04-25 14:44 UTC, kagame8732 approved these changes
Well implemented!

2023-04-25 14:58 UTC, merged