Ft profile page 184651336
atlp-rwanda/Team-furebo-E-commerce-bn pull request #57
Opened 2023-04-25 23:52 UTC by nshutip

#### What does this PR do?

Creates the User Profile page settings

#### Description of Task to be completed?

Have the following endpoints working

- `GET /api/profile`
- `PATCH /api/profile`

#### How should this be manually tested?

- Clone the repository
- Navigate to the project
- Create a .env file
- Add the following Variables in the .env file
  - JWT_SECRET
  - USER_SECRET_KEY
  - BCRYPT_KEY
  - TOKEN_EXPIRATION
  - SENDGRID_API_KEY
  - SENDER_EMAIL
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET
  - NODE_ENV
  - DB_USERNAME
  - DB_PASSWORD
  - DB_HOST
  - DB_NAME
  - RESET_URL

- In the terminal, run `npm install`, to install the required dependencies.
- RUN `npm start`
- Use Postman to test the all the endpoints
- or go to http://localhost:3000/api-docs/, to test all the endpoints

#### What are the relevant pivotal tracker/Trello stories?
#184651336

2023-04-27 07:48 UTC, JulesNIYOMWUNGERI approved these changes, later dismissed
good!

2023-04-27 17:25 UTC, kagame8732 requested changes, later dismissed
You have to squash the commits!!

2023-05-04 15:36 UTC, JulesNIYOMWUNGERI approved these changes

2023-05-04 15:38 UTC, ruberwa approved these changes

2023-05-04 16:14 UTC, merged