feat: add rate and review functionality
atlp-rwanda/Team-furebo-E-commerce-bn pull request #60
Opened 2023-05-01 16:04 UTC by bstwagir

#### What does this PR do?

This adds an API endpoint that a buyer will use to add a review and a rating to a purchased product. Once the request body has been validated and approved an instance of productFeedback will be generated and saved in the database in the ProductFeedback table with related metadata such as productId and userId. And an averageRating value will be generated and added to the reviewed product table, as an average of the sum of all the reviews left on the product.

#### Description of Task to be completed?

Have the following endpoints working
- `POST/api/addPrductFeedback/:id`
the :id in the route represents the productId, only a registered customer may create a review, and the rating value should be kept between 1 and 5.

#### How should this be manually tested?

- Clone the repository
- Navigate to the project
- Create a .env file
- Add the following Variables in the .env file
  - JWT_SECRET, USER_SECRET_KEY, BCRYPT_KEY, TOKEN_EXPIRATION
  - SENDGRID_API_KEY, SENDER_EMAIL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET
  - NODE_ENV
  - DB_USERNAME
  - DB_PASSWORD
  - DB_HOST
  - DB_NAME

- In the terminal, run `npm install`, to install the required dependencies.
- RUN `npm start`
- Use Postman to test all the endpoints
- or go to http://localhost:3000/api-docs/, to test all the endpoints

#### What are the relevant pivotal tracker/Trello stories?
 #184651347

2023-05-01 22:59 UTC, kagame8732 submitted a review, later dismissed
Working well!

2023-05-02 07:16 UTC, ruberwa requested changes
coverage and . nyc_output think can be better to be  in git ignore

2023-05-02 10:08 UTC, kagame8732 approved these changes, later dismissed
Working well!!

2023-05-02 10:13 UTC, ruberwa approved these changes, later dismissed

2023-05-02 11:45 UTC, nshutip approved these changes, later dismissed

2023-05-02 11:45 UTC, nshutip commented on src/middlewares/validateProductFeedbackMiddlware.js
> +import { Product } from '../Database/models';
All try/catch hooks should handle by the asyncWrapper from utils

2023-05-03 10:46 UTC, kagame8732 submitted a review, later dismissed

2023-05-03 11:33 UTC, ruberwa submitted a review, later dismissed

2023-05-03 22:38 UTC, ruberwa submitted a review, later dismissed

2023-05-03 22:42 UTC, kagame8732 submitted a review, later dismissed
Working well!

2023-05-04 06:30 UTC, nshutip requested changes, later dismissed
This PR has no functionalities now, it only has .gitignore in the files changed.
Make sure to commit all your code and push it again.

2023-05-10 14:44 UTC, JulesNIYOMWUNGERI approved these changes

2023-05-10 20:27 UTC, kagame8732 approved these changes

2023-05-10 20:29 UTC, nshutip commented on src/tests/create-product.test.js
why did you turn your tests to async functions?

2023-05-10 20:31 UTC, nshutip approved these changes

2023-05-11 09:02 UTC, merged