Updated README.md
atlp-rwanda/Team-furebo-E-commerce-bn pull request #7
Opened 2023-03-12 19:47 UTC by kagame8732

2023-03-12 20:38 UTC, Raphaela664 approved these changes, later dismissed

2023-03-14 12:23 UTC, nshutip requested changes, later dismissed
You have to squash the commits.

2023-03-14 16:40 UTC, bstwagir approved these changes, later dismissed
Great file. Approved.

2023-03-14 18:38 UTC, ruberwa approved these changes, later dismissed

2023-03-15 07:53 UTC, bahati10 approved these changes, later dismissed

2023-03-15 14:38 UTC, Raphaela664 submitted a review, later dismissed

2023-03-15 14:39 UTC, ruberwa submitted a review, later dismissed

2023-03-16 07:29 UTC, ruberwa approved these changes, later dismissed

2023-03-16 07:34 UTC, bahati10 submitted a review, later dismissed

2023-03-16 09:05 UTC, bstwagir approved these changes, later dismissed

2023-03-16 09:19 UTC, Raphaela664 approved these changes, later dismissed

2023-03-17 08:56 UTC, bahati10 submitted a review, later dismissed

2023-03-17 08:57 UTC, ruberwa approved these changes, later dismissed

2023-03-17 09:12 UTC, Raphaela664 submitted a review, later dismissed

2023-03-17 09:45 UTC, bstwagir approved these changes, later dismissed

2023-03-17 10:23 UTC, nshutip submitted a review, later dismissed

2023-03-17 12:53 UTC, ruberwa approved these changes

2023-03-17 12:53 UTC, bahati10 approved these changes

2023-03-18 07:40 UTC, nshutip submitted a review, later dismissed
Task well executed, but the PR description does not meet the engineering playbook standards.

2023-03-19 09:28 UTC, merged