Ft hound ci 184651323
atlp-rwanda/Team-furebo-E-commerce-bn pull request #8
Opened 2023-03-12 20:14 UTC by kagame8732

2023-03-12 20:37 UTC, Raphaela664 submitted a review, later dismissed

2023-03-13 07:42 UTC, heshima18 submitted a review, later dismissed

2023-03-13 17:50 UTC, nshutip requested changes
It seems like you installed the express dependency again, and inside index.js, you require the dotenv again(on line 8), yet It had already been done on line 4.

2023-03-13 18:51 UTC, nshutip approved these changes, later dismissed

2023-03-14 08:32 UTC, bstwagir requested changes
There seems a merge conflict with file .circleci/config.yml you might need to solve before merging.

2023-03-14 18:37 UTC, ruberwa approved these changes, later dismissed

2023-03-14 21:56 UTC, bahati10 approved these changes, later dismissed

2023-03-15 08:12 UTC, bstwagir approved these changes, later dismissed
conflicts well resolved.

2023-03-16 07:30 UTC, ruberwa approved these changes

2023-03-16 07:34 UTC, bahati10 approved these changes

2023-03-16 09:15 UTC, bstwagir approved these changes

2023-03-16 09:17 UTC, Raphaela664 approved these changes

2023-03-17 05:48 UTC, merged