chore: Set up ESLint and Git pre-commit hook
atlp-rwanda/Team-furebo-E-commerce-bn pull request #9
Opened 2023-03-12 20:34 UTC by Raphaela664

This PR adds the configuration for ESLint and Git pre-commit hook
to ensure code quality and prevent committing of code with syntax errors,
formatting issues, and failing tests.

To manually test, run npm run lint to check for linting errors,
npm run format to format the code using Prettier,
and npm test to run tests using Jest.

#184651322

2023-03-13 07:29 UTC, heshima18 approved these changes

2023-03-13 17:55 UTC, nshutip commented on package.json
> -    "test": "echo \"Error: no test specified\" && exit 1"
I believe that this line has to be removed, to avoid errors while testing

2023-03-13 17:56 UTC, nshutip reviewed
Well executed, just a few errors of repetition to correct.

2023-03-14 08:51 UTC, furebo requested changes
Please squash the commits to 1 commit and rebase to resolve the conflicts

2023-03-15 10:15 UTC, ruberwa submitted a review, later dismissed

2023-03-15 15:41 UTC, ruberwa approved these changes

2023-03-15 15:43 UTC, bahati10 approved these changes

2023-03-15 15:49 UTC, kagame8732 approved these changes

2023-03-15 15:53 UTC, bstwagir approved these changes

2023-03-17 05:42 UTC, furebo approved these changes

2023-03-17 05:42 UTC, merged